python lerobot/scripts/control_robot.py record \
    --robot-path lerobot/configs/robot/koch_jack.yaml \
    --fps 30 \
    --root with_rewards_2 \
    --repo-id jackvial/koch_test \
    --warmup-time-s 5 \
    --episode-time-s 20 \
    --reset-time-s 10 \
    --num-episodes 2 \
    --push-to-hub 1 \
    --assign-rewards 1 \
    --single-task test_description